name:                monaa2imitator
version:             0.1.0.0
github:              "MasWag/monaa2imitator"
license:             GPL-3
author:              "Masaki Waga"
maintainer:          "masakiwaga@gmail.com"
copyright:           "2019 Masaki Waga"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MasWag/monaa2imitator#readme>

dependencies:
  - base >= 4.7 && < 5
  - graphviz >= 2999.20.0.3
  - text
  - MissingH
  - parsec

library:
  source-dirs: src

executables:
  monaa2imitator:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monaa2imitator

tests:
  monaa2imitator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monaa2imitator
    - hspec
