name: hspec

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        plan:
        - { build: stack, resolver: "--resolver lts-14"  }   # ghc-8.6.5

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: test
      run: stack --no-terminal ${{ matrix.plan.resolver }} test
